local Mymenu = menu('Yeahz_riven', 'Yeahz Riven')

Mymenu:header('header_push', 'Panic clear')
Mymenu:boolean('push_w', 'Use W', true)
Mymenu:boolean('push_e', 'Use E', true)
Mymenu:keybind('push', 'Panic clear key', 'V', nil)

--Mymenu:header('header_harass', 'Harass')
--Mymenu:dropdown('harass_mode', 'Retreat Spell', 1, {'Q', 'E'})
--Mymenu:keybind('harass', 'Harass Key', 'T', nil)

--Mymenu:header('header_misc', 'Misc')
--Mymenu:boolean('cancel_q', 'Cancel Qs issued by yourself', true)

Mymenu:header('header_flash', 'Flash combo')
Mymenu:boolean('flash', 'Use flash combo on selected target', true)
Mymenu:boolean('reset_ts', 'Reset selected target after flash', true)
Mymenu:boolean('flash_only_r', 'Use flash only for r1/r2 combos', false)
Mymenu:slider('r2_flash', 'Flash after r2 missiles weight', 100, 0, 100, 1)

Mymenu:header('header_gap', 'Closing the first gap')
Mymenu:boolean('gap_e_w', 'E[+?]->[?[+W]]', true)
Mymenu:boolean('gap_e_q', 'E[+?]->[?[+Q]]', true)
Mymenu:boolean('gap_e_aa', 'E[+?]->[AA]', true)
Mymenu:boolean('gap_q', 'Q->[?]', true)
Mymenu:header('header_combat', 'Combat')
--Mymenu:boolean('auto_cancel', 'Silently cancel manual Q', true)
--Mymenu:menu('e_gapclose', 'Initial Gapclose')
--menu.e_gapclose:boolean('e_w', 'Use E->W[+Q]', true)
--menu.e_gapclose:boolean('e_q', 'Use E->Q', true)
--menu.e_gapclose:boolean('e_aa', 'Use E->AA', true)
--menu.e_gapclose:boolean('q_aa', 'Use Q->AA', true)
Mymenu:slider('e_double_cast_weight', 'Close combat double cast weight', 100, 0, 100, 1)
Mymenu:keybind('e_aa', 'Consider E[+?]->[AA->[?]]', nil, 'T')
Mymenu:keybind('r1', 'Use R1 in next combo', nil, 'C')
Mymenu:keybind('combat', 'Combat key', 'Space', nil)
Mymenu:menu('flee_setting', 'Flee setting')
Mymenu.flee_setting:keybind('flee', 'Flee key', 'Z', nil)
Mymenu.flee_setting:dropdown('quickrun', 'Save Q3,E Modifier', 2, {'None', 'LBM Down', 'Hotkey',})
return Mymenu